### ISSUE TITLE
Docker container crashes directly after starting

### ISSUE THREAD

**Issue by uherbstsolace** [solacecommunity/solace-prometheus-exporter#27]
Hi,
I just tried to install the exporter as documented in README as docker container and the container instantly crashes with:

```
uherbst@aya:~/prometheus-exporter$ docker logs solace-exporter
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x83b1be]

goroutine 1 [running]:
gopkg.in/ini%2ev1.(*File).Sections(0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/gopkg.in/ini.v1@v1.51.1/file.go:146 +0x4e
main.parseConfig(0x0, 0x0, 0xc000140000, 0xa50200, 0xc000132390, 0xc0000ee280, 0x8)
        /go/src/app/solace_prometheus_exporter.go:1424 +0x3f5
main.main()
        /go/src/app/solace_prometheus_exporter.go:1542 +0x32f

```

Any ideas ?

my docker run command is this:
```
docker run -d \
  -p 9628:9628 \
  --env-file env.txt \
  --name solace-exporter \
  solacecommunity/solace-prometheus-exporter

```

my env.txt is this:
```
SOLACE_LISTEN_ADDR=0.0.0.0:9628
SOLACE_SCRAPE_URI=https://xxx:443
SOLACE_USERNAME=abc
SOLACE_PASSWORD=pw
SOLACE_TIMEOUT=5s
SOLACE_SSL_VERIFY=false
```

**Comment by GreenRover** [comment]
Fixed with: https://github.com/solacecommunity/solace-prometheus-exporter/commit/54e1b5916a4d72f746a34bfc656cea478fa49162
